# Generated by Django 3.1.7 on 2022-10-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='issue_a',
            new_name='BLUE_TEAM',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='issue_b',
            new_name='RED_TEAM',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('RED TEAM', 'RED TEAM'), ('BLUE TEAM', 'BLUE TEAM')], default='RED TEAM', max_length=10),
        ),
    ]
