# Generated by Django 3.1.7 on 2022-10-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0002_auto_20221006_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(max_length=10),
        ),
    ]
